# workflow copied from:
# https://github.com/operationcanard/monorepo-template/blob/master/.github/workflows/workflow_pre_commit_check.yml
name: Run and check pre-commit hooks

on: workflow_call

jobs:
  check-hooks:
    name: Run pre-commit hooks on modified files
    runs-on: ubuntu-latest
    steps:
      - name: üõÇ Query modified files
        id: filter
        # Action to get changed files
        uses: dorny/paths-filter@668c092af3649c4b664c54e4b704aa46782f6f7c
        with:
          # To get the list of files as parameters in a command (space separation)
          list-files: "shell"
          # Filters that check which files were changed to have appropriate rules
          filters: |
            pre-commit-config:
              - '.pre-commit-config.yaml'
            changed:
              - '**'

      - name: üìÇ Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: üêç Set up Python 3.10
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.10"

      - name: üì• Install pre-commit
        run: python -m pip install pre-commit

      - name: üíæ cache pre-commit output files
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: ‚ñ∂Ô∏è Run pre-commit on all files if '.pre-commit-config.yaml' updated
        if: ${{ steps.filter.outputs.pre-commit-config == 'true' }}
        run: pre-commit run --show-diff-on-failure --color=always --all-files

      - name: ‚ñ∂Ô∏è Run pre-commit on changed files
        if: ${{ steps.filter.outputs.pre-commit-config == 'false' }}
        run: pre-commit run --show-diff-on-failure --color=always --files ${{ steps.filter.outputs.changed_files }}
